##
## Experiment: task46
##
## where trials in { 10, 50, 100, 500, 1000, 5000, 10000 }, par = 0.5, nexp = 10%
##


#executable	= /home-users/nlipo/blai/learning-depth-first-search-read-only/race/race
executable	= /home-users/nlipo/blai/Aldo/example.sh
universe	= vanilla
#Requirements	= Memory >= 1928
InitialDir	= /home-users/nlipo/blai/Aldo
should_transfer_files	= YES
when_to_transfer_output	= ON_EXIT
#transfer_input_files	= \
#/home-users/nlipo/blai/learning-depth-first-search-read-only/race/tracks/barto-small.track,\
#/home-users/nlipo/blai/learning-depth-first-search-read-only/race/tracks/barto-big.track

#arguments = -D 0.5 -h 11 -s 0 -p 0.7 barto-big.track min-min aot-value 10 50 0.5 5
arguments = -lR
output = output.1
queue
arguments = -lR
output = output.2
queue

