(define (problem p)
	(:domain qbf)
	(:objects 			obj1 
			obj2 
			obj3 
			obj4 
			obj5 
			obj6 
			obj7 
			obj8 
			obj9 

	)
	(:init
		(begin)
		(suc zero obj1)
		(suc obj1 obj2)
		(suc obj2 obj3)
		(suc obj3 obj4)
		(suc obj4 obj5)
		(suc obj5 obj6)
		(suc obj6 obj7)
		(suc obj7 obj8)
		(suc obj8 obj9)
		(suc obj9 max)
		(so-forall_suc_t zero obj1)
		(so-forall_suc_t obj1 obj2)
		(so-forall_suc_t obj2 obj3)
		(so-forall_zero_t zero)
		(so-forall_max_t obj3)
		(not_t zero)
		(not_t obj1)
		(not_t obj2)
		(not_t obj3)
		(not_e zero)
		(not_e obj1)
		(not_e obj2)
		(not_e obj3)
		(not_r obj4)
		(not_r obj5)
		(not_r obj6)
		(not_r obj7)
		(not_r obj8)
		(not_r obj9)
		(not_r max)
		(e obj4)
		(e obj5)
		(e obj6)
		(e obj7)
		(e obj8)
		(e obj9)
		(e max)
		(N obj3 zero)
		(N obj1 zero)
		(P obj6 zero)
		(P max zero)
		(P obj9 zero)
		(P obj3 obj1)
		(P obj2 obj1)
		(P obj7 obj1)
		(P obj5 obj1)
		(P max obj1)
		(P obj2 obj2)
		(N zero obj2)
		(P obj9 obj2)
		(N obj6 obj2)
		(P obj8 obj2)
		(P zero obj3)
		(P obj3 obj3)
		(P obj8 obj3)
		(N obj9 obj3)
		(N max obj3)
		(N obj2 obj4)
		(P obj3 obj4)
		(P obj8 obj4)
		(P obj9 obj4)
		(P obj7 obj4)
		(N obj1 obj5)
		(P obj2 obj5)
		(P obj4 obj5)
		(N obj7 obj5)
		(P obj8 obj5)
		(P obj1 obj6)
		(N obj2 obj6)
		(N obj5 obj6)
		(P obj4 obj6)
		(P obj6 obj6)
		(P obj2 obj7)
		(P obj1 obj7)
		(N obj9 obj7)
		(P obj7 obj7)
		(N obj5 obj7)
		(P obj2 obj8)
		(P obj1 obj8)
		(P obj7 obj8)
		(N obj9 obj8)
		(N obj8 obj8)
		(P obj3 obj9)
		(N obj1 obj9)
		(N obj9 obj9)
		(N obj8 obj9)
		(P obj7 obj9)
	)
	(:goal (holds_goal)
	)
)