(define (problem p)
	(:domain qbf)
	(:objects 			obj1 
			obj2 
			obj3 
			obj4 

	)
	(:init
		(begin)
		(suc zero obj1)
		(suc obj1 obj2)
		(suc obj2 obj3)
		(suc obj3 obj4)
		(suc obj4 max)
		(so-forall_suc_t zero obj1)
		(so-forall_suc_t obj1 obj2)
		(so-forall_suc_t obj2 obj3)
		(so-forall_zero_t zero)
		(so-forall_max_t obj3)
		(not_t zero)
		(not_t obj1)
		(not_t obj2)
		(not_t obj3)
		(not_e zero)
		(not_e obj1)
		(not_e obj2)
		(not_e obj3)
		(not_r obj4)
		(not_r max)
		(e obj4)
		(e max)
		(P zero zero)
		(P obj4 zero)
		(P max zero)
		(P obj2 obj1)
		(N max obj1)
		(N obj4 obj1)
		(N obj3 obj2)
		(P obj4 obj2)
		(P max obj2)
		(N obj1 obj3)
		(P max obj3)
		(N obj4 obj3)
		(P obj3 obj4)
		(N obj4 obj4)
		(N max obj4)
		(N obj3 max)
		(N max max)
		(N obj4 max)
	)
	(:goal (holds_goal)
	)
)