(define (problem p)
	(:domain qbf)
	(:objects 			obj1 
			obj2 
			obj3 
			obj4 
			obj5 
			obj6 
			obj7 
			obj8 

	)
	(:init
		(begin)
		(suc zero obj1)
		(suc obj1 obj2)
		(suc obj2 obj3)
		(suc obj3 obj4)
		(suc obj4 obj5)
		(suc obj5 obj6)
		(suc obj6 obj7)
		(suc obj7 obj8)
		(suc obj8 max)
		(so-forall_suc_t zero obj1)
		(so-forall_zero_t zero)
		(so-forall_max_t obj1)
		(not_t zero)
		(not_t obj1)
		(not_e zero)
		(not_e obj1)
		(not_r obj2)
		(not_r obj3)
		(not_r obj4)
		(not_r obj5)
		(not_r obj6)
		(not_r obj7)
		(not_r obj8)
		(e obj2)
		(e obj3)
		(e obj4)
		(e obj5)
		(e obj6)
		(e obj7)
		(e obj8)
		(N obj1 zero)
		(P obj6 zero)
		(N obj7 zero)
		(N obj5 zero)
		(P zero obj1)
		(N obj7 obj1)
		(P obj5 obj1)
		(N obj3 obj1)
		(P zero obj2)
		(N obj3 obj2)
		(N obj2 obj2)
		(N obj5 obj2)
		(N zero obj3)
		(P obj7 obj3)
		(N obj2 obj3)
		(P obj6 obj3)
		(P obj1 obj4)
		(N obj3 obj4)
		(N obj2 obj4)
		(P obj4 obj4)
		(P zero obj5)
		(P obj8 obj5)
		(P obj3 obj5)
		(N obj6 obj5)
		(N zero obj6)
		(P obj8 obj6)
		(P obj6 obj6)
		(P obj5 obj6)
		(N obj1 obj7)
		(N obj4 obj7)
		(N obj7 obj7)
		(N obj8 obj7)
		(P zero obj8)
		(N obj5 obj8)
		(P obj6 obj8)
		(N obj7 obj8)
		(N zero max)
		(N obj5 max)
		(N obj6 max)
		(N obj2 max)
	)
	(:goal (holds_goal)
	)
)