(define (problem p)
	(:domain qbf)
	(:objects 			obj1 

	)
	(:init
		(begin)
		(suc zero obj1)
		(suc obj1 max)
		(so-forall_suc_t zero obj1)
		(so-forall_zero_t zero)
		(so-forall_max_t obj1)
		(not_t zero)
		(not_t obj1)
		(not_e zero)
		(not_e obj1)
		(not_r max)
		(e max)
		(N obj1 zero)
		(P max zero)
		(P zero obj1)
		(N max obj1)
		(P obj1 max)
		(P max max)
	)
	(:goal (holds_goal)
	)
)