(define (problem p)
	(:domain qbf)
	(:objects 			obj1 
			obj2 

	)
	(:init
		(begin)
		(suc zero obj1)
		(suc obj1 obj2)
		(suc obj2 max)
		(so-forall_suc_t zero obj1)
		(so-forall_zero_t zero)
		(so-forall_max_t obj1)
		(not_t zero)
		(not_t obj1)
		(not_e zero)
		(not_e obj1)
		(not_r obj2)
		(not_r max)
		(e obj2)
		(e max)
		(P obj1 zero)
		(P zero zero)
		(P max zero)
		(P obj1 obj1)
		(N zero obj1)
		(N max obj1)
	)
	(:goal (holds_goal)
	)
)