#! /bin/bash

tar cfz prev-solutions/solutions_`date "+%Y:%m:%d_%H:%M:%S"`.tar.gz solutions-soforall 

if [ -z $1 ];
then
    echo "Correct usage <./setup-soforall -all|-solve|-totalize>"
else 
    if [ $1 = -all ]; 
    then
        rm -rf problems-soforall
        rm -rf solutions-soforall

        for i in `ls domains/so-forall/ | grep .dct | sed -e s/.dct$//`; do    
            mkdir -p problems-soforall/$i

            tool/soplan.py --output=problems-soforall/$i/$i.pddl domains/so-forall/$i.dct\
            > /dev/null
                echo "Created domain for $i"
        done
        ./scripts/so-forall/get_all_directories_soforall.py
        ./scripts/so-forall/create_problems_soforall.py
        ./scripts/so-forall/solve_all_forall.py
    
    elif [ $1 = -solve ]; 
    then
        rm -rf solutions-soforall
    
        ./scripts/so-forall/get_solutions_directories_soforall.py
        ./scripts/so-forall/solve_all_forall.py
        
    elif [ $1 = -totalize ]; 
    then
        ./scripts/so-forall/totalize.py
    else
        echo "Correct usage <./setup-soforall -all|-solve|-totalize>"
    fi
fi