#! /usr/bin/env bash
rm -rf problems-soforall
rm -rf condor_submits

mkdir -p condor_submits
for i in `ls domains/so-forall/ | grep .dct | sed -e s/.dct$//`; do    
    mkdir -p problems-soforall/$i

    tool/soplan.py --output=problems-soforall/$i/$i.pddl domains/so-forall/$i.dct\
    > /dev/null
        echo "Created domain for $i"
done
./scripts/so-forall/get_problem_directories_soforall.py
./scripts/so-forall/create_problems_soforall.py
