(define (problem a)
	(:domain ramsey)
	(:objects
		obj1
		obj2
		obj3
		obj4
	)
	(:init
		(begin)
		(suc zero obj1)
		(suc obj1 obj2)
		(suc obj2 obj3)
		(suc obj3 obj4)
		(suc obj4 max)
		(so-forall_suc_t zero obj1)
		(so-forall_suc_t obj1 obj2)
		(so-forall_suc_t obj2 obj3)
		(so-forall_suc_t obj3 obj4)
		(so-forall_suc_t obj4 max)
		(so-forall_zero_t zero)
		(so-forall_max_t max)
		(not_t zero zero)
		(not_t zero obj1)
		(not_t zero obj2)
		(not_t zero obj3)
		(not_t zero obj4)
		(not_t zero max)
		(not_t obj1 zero)
		(not_t obj1 obj1)
		(not_t obj1 obj2)
		(not_t obj1 obj3)
		(not_t obj1 obj4)
		(not_t obj1 max)
		(not_t obj2 zero)
		(not_t obj2 obj1)
		(not_t obj2 obj2)
		(not_t obj2 obj3)
		(not_t obj2 obj4)
		(not_t obj2 max)
		(not_t obj3 zero)
		(not_t obj3 obj1)
		(not_t obj3 obj2)
		(not_t obj3 obj3)
		(not_t obj3 obj4)
		(not_t obj3 max)
		(not_t obj4 zero)
		(not_t obj4 obj1)
		(not_t obj4 obj2)
		(not_t obj4 obj3)
		(not_t obj4 obj4)
		(not_t obj4 max)
		(not_t max zero)
		(not_t max obj1)
		(not_t max obj2)
		(not_t max obj3)
		(not_t max obj4)
		(not_t max max)
		(not_f zero zero)
		(not_f zero obj1)
		(not_f zero obj2)
		(not_f zero obj3)
		(not_f zero obj4)
		(not_f zero max)
		(not_f obj1 zero)
		(not_f obj1 obj1)
		(not_f obj1 obj2)
		(not_f obj1 obj3)
		(not_f obj1 obj4)
		(not_f obj1 max)
		(not_f obj2 zero)
		(not_f obj2 obj1)
		(not_f obj2 obj2)
		(not_f obj2 obj3)
		(not_f obj2 obj4)
		(not_f obj2 max)
		(not_f obj3 zero)
		(not_f obj3 obj1)
		(not_f obj3 obj2)
		(not_f obj3 obj3)
		(not_f obj3 obj4)
		(not_f obj3 max)
		(not_f obj4 zero)
		(not_f obj4 obj1)
		(not_f obj4 obj2)
		(not_f obj4 obj3)
		(not_f obj4 obj4)
		(not_f obj4 max)
		(not_f max zero)
		(not_f max obj1)
		(not_f max obj2)
		(not_f max obj3)
		(not_f max obj4)
		(not_f max max)
		(k1 zero)
		(k1 obj1)
		(k1 obj2)
		(k2 zero)
		(k2 obj1)
		(k2 obj2)
		(free_domain_f zero)
		(free_domain_f obj1)
		(free_domain_f obj2)
		(free_domain_f obj3)
		(free_domain_f obj4)
		(free_domain_f max)
		(free_range_f zero)
		(free_range_f obj1)
		(free_range_f obj2)
		(free_range_f obj3)
		(free_range_f obj4)
		(free_range_f max)
	)
	(:goal (holds_goal)
	)
)